### ISSUE TITLE
Requirement.parse('pyasn1<0.5.0,>=0.4.1')

### ISSUE THREAD

**Issue by ahegde3** [nurdtechie98/drive-cli#22]
### I tried using the application.When I try drive login or any other command it gives me an error.The traceback is as follow.
Traceback (most recent call last):
  File "/home/ahegde3/anaconda3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/home/ahegde3/anaconda3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/ahegde3/anaconda3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 875, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyasn1 0.1.9 (/home/ahegde3/anaconda3/lib/python3.5/site-packages), Requirement.parse('pyasn1<0.5.0,>=0.4.1'), {'pyasn1-modules'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ahegde3/anaconda3/bin/drive", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/ahegde3/anaconda3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3144, in <module>
    @_call_aside
  File "/home/ahegde3/anaconda3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3128, in _call_aside
    f(*args, **kwargs)
  File "/home/ahegde3/anaconda3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3157, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/ahegde3/anaconda3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 668, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/ahegde3/anaconda3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 681, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/ahegde3/anaconda3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 875, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyasn1 0.1.9 (/home/ahegde3/anaconda3/lib/python3.5/site-packages), Requirement.parse('pyasn1<0.5.0,>=0.4.1'), {'pyasn1-modules'})

### Didnt find any solution .

**Comment by nurdtechie98** [comment]
@ahegde3 According to the error:
The required pyasn1 version should be greater or equal to 0.4.1 and less than 0.5.0 and you currently have installed v0.1.9.
try updating manually to a specific version run
`pip install pyasn1 --upgrade` 
this will update your current pyasn1 package to the latest version and should solve the problem.

**Comment by ahegde3** [comment]
Yes,it worked.Thanks

**Comment by Misby** [comment]
> @ahegde3根据错误提示：
> 所需的pyasn1版本应大于等于0.4.1小于0.5.0且您目前安装的是v0.1.9。
> 尝试手动更新到特定版本运行
> `pip install pyasn1 --upgrade`
> 这会将您当前的 pyasn1 包更新到最新版本，并且应该可以解决问题。
> 
> 请让我知道它是否有效



> @ahegde3根据错误提示：
> 所需的pyasn1版本应大于等于0.4.1小于0.5.0且您目前安装的是v0.1.9。
> 尝试手动更新到特定版本运行
> `pip install pyasn1 --upgrade`
> 这会将您当前的 pyasn1 包更新到最新版本，并且应该可以解决问题。
> 
> 请让我知道它是否有效

Thanks it works
