### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by epetros** [nurdtechie98/drive-cli#74]
Greatings,
Unfortunatly am getting the following error while trying to upload to drive a 1GB file:

Traceback (most recent call last):
  File "/usr/local/bin/drive", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/drive_cli/actions.py", line 169, in create_remote
    utils.upload_file(file, file_path, pid)
  File "/usr/local/lib/python3.5/dist-packages/drive_cli/utils.py", line 375, in upload_file
    fields='id').execute()
  File "/usr/local/lib/python3.5/dist-packages/googleapiclient/discovery.py", line 858, in method
    payload = media_upload.getbytes(0, media_upload.size())
  File "/usr/local/lib/python3.5/dist-packages/googleapiclient/http.py", line 486, in getbytes
    return self._fd.read(length)
MemoryError

Am running in a Google Cloud Platform machine -n1-standard-1 (1 vCPU, 3.75 GB memory).

**Comment by JakeCow** [comment]
I am experiencing same issue while trying to upload a file (+6gb).
Python is 64 bit. I was worried I had installed 32 bit by mistake.

**Comment by heylookltsme** [comment]
I'm seeing this same error when downloading a large (1.6 GB) file. 😞
