### ISSUE TITLE
TypeError during Push and Pull causes sync to fail (TypeError: '<' not supported between instances of 'dict' and 'float')

### ISSUE THREAD

**Issue by sarthak7gupta** [nurdtechie98/drive-cli#75]
$ drive push
checking for changes in 'myFolderName' ....
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/drive", line 10, in <module>
    sys.exit(cli())
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/drive_cli/actions.py", line 311, in push
    utils.push_content(cwd, fid)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/drive_cli/utils.py", line 487, in push_content
    push_content(child_cwd, child_id)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/drive_cli/utils.py", line 494, in push_content
    if(push_needed(drive_lis[item], item_path)):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/drive_cli/utils.py", line 173, in push_needed
    if sync_time < local_time:
TypeError: '<' not supported between instances of 'dict' and 'float'

$ drive pull
checking for changes in 'myFolderName' ....
Preparing: myFilename.ext for download
downloading file  [####################################]  100%
completed download of myFilename.ext
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/drive", line 10, in <module>
    sys.exit(cli())
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/drive_cli/actions.py", line 290, in pull
    utils.pull_content(cwd, fid)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/drive_cli/utils.py", line 422, in pull_content
    if((not os.path.exists(dir_name)) or write_needed(dir_name, item)):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/drive_cli/utils.py", line 154, in write_needed
    if(sync_time < drive_time):
TypeError: '<' not supported between instances of 'dict' and 'float'

**Comment by NightWing1998** [comment]
Can you please be more specific on how to recreate this error??

**Comment by sarthak7gupta** [comment]
To be honest, it works sometimes, and sometimes it doesn't. When doing a simple `drive push` or `drive pull`, it works till some files, and then crashed giving the above error
