### ISSUE TITLE
OverflowError: string longer than 2147483647 bytes

### ISSUE THREAD

**Issue by lamhoangtung** [nurdtechie98/drive-cli#77]
Hi, I'm trying to upload a 15GB file from an AWS server to my Google Drive, the server have 32 cores and 480GB of RAM.

After a while, I got this error

```python
linus@srv-aws:~/linus$ drive add_remote --file xxx.zip
Traceback (most recent call last):
  File "/mnt/data/linus/.local/bin/drive", line 10, in <module>
    sys.exit(cli())
  File "/mnt/data/linus/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/data/linus/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/mnt/data/linus/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/data/linus/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/data/linus/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/mnt/data/linus/.local/lib/python3.6/site-packages/drive_cli/actions.py", line 169, in create_remote
    utils.upload_file(file, file_path, pid)
  File "/mnt/data/linus/.local/lib/python3.6/site-packages/drive_cli/utils.py", line 375, in upload_file
    fields='id').execute()
  File "/mnt/data/linus/.local/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/mnt/data/linus/.local/lib/python3.6/site-packages/googleapiclient/http.py", line 846, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/mnt/data/linus/.local/lib/python3.6/site-packages/googleapiclient/http.py", line 164, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/mnt/data/linus/.local/lib/python3.6/site-packages/oauth2client/transport.py", line 175, in new_request
    redirections, connection_type)
  File "/mnt/data/linus/.local/lib/python3.6/site-packages/oauth2client/transport.py", line 282, in request
    connection_type=connection_type)
  File "/mnt/data/linus/.local/lib/python3.6/site-packages/httplib2/__init__.py", line 1926, in request
    cachekey,
  File "/mnt/data/linus/.local/lib/python3.6/site-packages/httplib2/__init__.py", line 1595, in _request
    conn, request_uri, method, body, headers
  File "/mnt/data/linus/.local/lib/python3.6/site-packages/httplib2/__init__.py", line 1502, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.6/ssl.py", line 975, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.6/ssl.py", line 944, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
OverflowError: string longer than 2147483647 bytes
```

Any ideal how to resolve this everyone ? Thanks a lot ;)

**Comment by DmitriyG228** [comment]
HI, still have this issue,

`  File "/home/dima/drive-cli/drive_cli/actions.py", line 178, in create_remote
    utils.push_content(child_cwd, child_id)
  File "/home/dima/drive-cli/drive_cli/utils.py", line 492, in push_content
    upload_file(item, item_path, fid)
  File "/home/dima/drive-cli/drive_cli/utils.py", line 375, in upload_file
    fields='id').execute()
  File "/home/dima/anaconda3/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/dima/anaconda3/lib/python3.7/site-packages/googleapiclient/http.py", line 846, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/home/dima/anaconda3/lib/python3.7/site-packages/googleapiclient/http.py", line 164, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/home/dima/anaconda3/lib/python3.7/site-packages/oauth2client/transport.py", line 175, in new_request
    redirections, connection_type)
  File "/home/dima/anaconda3/lib/python3.7/site-packages/oauth2client/transport.py", line 282, in request
    connection_type=connection_type)
  File "/home/dima/anaconda3/lib/python3.7/site-packages/httplib2/__init__.py", line 1926, in request
    cachekey,
  File "/home/dima/anaconda3/lib/python3.7/site-packages/httplib2/__init__.py", line 1595, in _request
    conn, request_uri, method, body, headers
  File "/home/dima/anaconda3/lib/python3.7/site-packages/httplib2/__init__.py", line 1502, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/home/dima/anaconda3/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/dima/anaconda3/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/dima/anaconda3/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/dima/anaconda3/lib/python3.7/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/home/dima/anaconda3/lib/python3.7/http/client.py", line 987, in send
    self.sock.sendall(data)
  File "/home/dima/anaconda3/lib/python3.7/ssl.py", line 1034, in sendall
    v = self.send(byte_view[count:])
  File "/home/dima/anaconda3/lib/python3.7/ssl.py", line 1003, in send
    return self._sslobj.write(data)
OverflowError: string longer than 2147483647 bytes `
