### ISSUE TITLE
NameError: name 'dir_name' is not defined when doing push

### ISSUE THREAD

**Issue by DmitriyG228** [nurdtechie98/drive-cli#98]
Hi, while doing push, I am getting the following error:

Traceback (most recent call last):
  File "/home/dima/anaconda3/bin/drive", line 11, in <module>
    load_entry_point('drive-cli', 'console_scripts', 'drive')()
  File "/home/dima/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/dima/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/dima/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dima/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dima/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/dima/drive-cli/drive_cli/actions.py", line 311, in push
    utils.push_content(cwd, fid)
  File "/home/dima/drive-cli/drive_cli/utils.py", line 487, in push_content
    push_content(child_cwd, child_id)
  File "/home/dima/drive-cli/drive_cli/utils.py", line 494, in push_content
    if(push_needed(drive_lis[item], item_path)):
  File "/home/dima/drive-cli/drive_cli/utils.py", line 178, in push_needed
    dir_name + " has been modified\npress o to OVERWRITE s to SKIP")
NameError: name 'dir_name' is not defined

**Comment by nandzi** [comment]
This was simply due to a variable naming error, see #101. I have noticed, however, that sometimes files are marked as having been modified both locally and remotely, when they haven't... Will make another issue sometime.
